---
chdir: /home/www-data/r13-team-90/
environment: production
address: 0.0.0.0
port: 8080
timeout: 30
log: /home/www-data/log/thin.log
pid: /home/www-data/pid/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 30
servers: 2
daemonize: true